/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package simuladorascensor;

/**
 *
 * @author admin
 */

import com.formdev.flatlaf.themes.FlatMacDarkLaf;

import javax.swing.Timer;
import javax.swing.UIManager;
import java.util.*;
import javax.swing.*;

public class ventana extends javax.swing.JFrame {
    
    private Timer timerAnimacion;
    private Timer timerPausa;
    private Queue<Integer> colaDestinos = new LinkedList<>();
    private boolean animacionEnCurso = false;
    private int destinoActual = -1;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ventana.class.getName());

    /**
     * Creates new form ventana
     */
    public ventana() {

        
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        label_llamar3 = new javax.swing.JLabel();
        label_llamar2 = new javax.swing.JLabel();
        label_llamar1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        piso1 = new javax.swing.JToggleButton();
        piso2 = new javax.swing.JToggleButton();
        piso3 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        numero = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        piso3edificio = new javax.swing.JToggleButton();
        piso1edificio = new javax.swing.JToggleButton();
        piso2edificio = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        flechaAscensor = new javax.swing.JLabel();
        slider = new javax.swing.JSlider();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_llamar3.setFont(new java.awt.Font("sansserif", 1, 30)); // NOI18N
        label_llamar3.setText("Piso 3");

        label_llamar2.setFont(new java.awt.Font("sansserif", 1, 30)); // NOI18N
        label_llamar2.setText("Piso 2");

        label_llamar1.setFont(new java.awt.Font("sansserif", 1, 30)); // NOI18N
        label_llamar1.setText("Piso 1");

        piso1.setBackground(new java.awt.Color(204, 0, 0));
        piso1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        piso1.setText("1");
        piso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piso1ActionPerformed(evt);
            }
        });

        piso2.setBackground(new java.awt.Color(204, 0, 0));
        piso2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        piso2.setText("2");
        piso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piso2ActionPerformed(evt);
            }
        });

        piso3.setBackground(new java.awt.Color(204, 0, 0));
        piso3.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        piso3.setText("3");
        piso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piso3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel2.setText("Piso");

        numero.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        numero.setText("3");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel4.setText("Ascensor ");

        labelDireccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDireccion.setForeground(new java.awt.Color(204, 0, 0));
        labelDireccion.setText("●");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(piso3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(piso2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(piso1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelDireccion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numero))
                .addGap(18, 18, 18)
                .addComponent(piso3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(piso2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(piso1)
                .addGap(20, 20, 20))
        );

        piso3edificio.setBackground(new java.awt.Color(204, 0, 0));
        piso3edificio.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        piso3edificio.setText("llamar 3");
        piso3edificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piso3edificioActionPerformed(evt);
            }
        });

        piso1edificio.setBackground(new java.awt.Color(204, 0, 0));
        piso1edificio.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        piso1edificio.setText("llamar 1");
        piso1edificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piso1edificioActionPerformed(evt);
            }
        });

        piso2edificio.setBackground(new java.awt.Color(204, 0, 0));
        piso2edificio.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        piso2edificio.setText("llamar 2");
        piso2edificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piso2edificioActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel5.setText("Edificio");

        flechaAscensor.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        flechaAscensor.setForeground(new java.awt.Color(204, 0, 0));
        flechaAscensor.setText("▲ - ASCENSOR ");

        slider.setMaximum(150);
        slider.setOrientation(javax.swing.JSlider.VERTICAL);
        slider.setValue(150);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(flechaAscensor)
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flechaAscensor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        if (getContentPane().getLayout() != null) {
            getContentPane().setLayout(null);
        }

        // Agregar la flecha
        getContentPane().add(flechaAscensor);
        flechaAscensor.setBounds(0, 0, 30, 30); // Tamaño inicial

        // Posicionar inicialmente
        posicionarFlechaEnSlider();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_llamar3)
                    .addComponent(label_llamar1)
                    .addComponent(label_llamar2)
                    .addComponent(piso3edificio)
                    .addComponent(piso2edificio)
                    .addComponent(piso1edificio))
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(label_llamar3)
                        .addGap(18, 18, 18)
                        .addComponent(piso3edificio)
                        .addGap(36, 36, 36)
                        .addComponent(label_llamar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(piso2edificio)
                        .addGap(33, 33, 33)
                        .addComponent(label_llamar1)
                        .addGap(18, 18, 18)
                        .addComponent(piso1edificio)))
                .addGap(85, 85, 85))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void actualizarDireccion(int valorActual, int valorDestino) {
    if (labelDireccion == null) return;
    
    if (valorDestino > valorActual) {
        labelDireccion.setText("▲");
        labelDireccion.setForeground(java.awt.Color.RED);
    } else if (valorDestino < valorActual) {
        labelDireccion.setText("▼");
        labelDireccion.setForeground(java.awt.Color.RED);
    } else {
        labelDireccion.setText("●");
        labelDireccion.setForeground(java.awt.Color.WHITE);
    }
}

    
    private void solicitarPiso(int valorDestino) {

        if (valorDestino == slider.getValue()) {
           
            return;
        }


        if (animacionEnCurso) {
         
            if (!colaDestinos.isEmpty() && estaEnMismaDireccion(valorDestino)) {
                colaDestinos.poll(); 
            }
            colaDestinos.offer(valorDestino);
           
        } else {
           
            iniciarAnimacion(valorDestino);
        }
    }


    private boolean estaEnMismaDireccion(int nuevoDestino) {
        int current = slider.getValue();
        int direccionActual = Integer.compare(destinoActual, current);
        int direccionNueva = Integer.compare(nuevoDestino, current);
        return direccionActual == direccionNueva;
    }
    
    private void actualizarPosicionFlecha(int valorSlider) {
        if (flechaAscensor == null || slider == null) return;
        
     
        int x = slider.getX() + slider.getWidth() + 10; 
        
       
        int y = calcularYDesdeValorSlider(valorSlider);
        
       
        y -= 10; 
        
     
        flechaAscensor.setLocation(x, y);
        

        flechaAscensor.setVisible(true);
      
        flechaAscensor.repaint();
    }
    
    private int calcularYDesdeValorSlider(int valor) {
        if (slider == null) return 0;
        
        int min = slider.getMinimum();
        int max = slider.getMaximum();
        int alturaSlider = slider.getHeight();
        int ySlider = slider.getY();
        

        float porcentaje = 1.0f - (float)(valor - min) / (max - min);
        

        int yEnSlider = (int)(porcentaje * alturaSlider);
        

        return ySlider + yEnSlider;
    }
   
    
    private void posicionarFlechaEnSlider() {
        if (flechaAscensor == null || slider == null) return;

     
        int valor = slider.getValue();

        int x = slider.getX() + slider.getWidth() + 15; 

     
        int y = calcularPosicionY(valor);

       
        flechaAscensor.setLocation(x, y);

      
        flechaAscensor.repaint();
    }

      
      
    private int calcularPosicionY(int valor) {
     
        int min = slider.getMinimum();  
        int max = slider.getMaximum();  
        int altura = slider.getHeight(); 
        int yBase = slider.getY();      


        float porcentaje = 1.0f - ((float)(valor - min) / (max - min));


        int posicionEnSlider = (int)(porcentaje * altura);


        return yBase + posicionEnSlider - (flechaAscensor.getHeight() / 2);
    }

        
        private void iniciarAnimacion(int valorDestino) {
            animacionEnCurso = true;
            destinoActual = valorDestino;

            int valorActual = slider.getValue();

            
            actualizarDireccion(valorActual, valorDestino);

            posicionarFlechaEnSlider();


            actualizarVisualizacionPiso(valorActual);

            if (valorActual == valorDestino) {
                iniciarPausa(valorDestino);
                return;
            }

            int duracionTotal = 2000; 
            int distancia = Math.abs(valorDestino - valorActual);
            int intervalo = Math.max(20, duracionTotal / distancia);

            if (timerAnimacion != null && timerAnimacion.isRunning()) {
                timerAnimacion.stop();
            }

            timerAnimacion = new Timer(intervalo, e -> {
                int currentValue = slider.getValue();
                int nuevoValor = currentValue;

                if (valorDestino > currentValue) {
                    nuevoValor = currentValue + 1;
                } else if (valorDestino < currentValue) {
                    nuevoValor = currentValue - 1;
                }

  
                slider.setValue(nuevoValor);

       
                posicionarFlechaEnSlider();

       
                actualizarLabelPiso(nuevoValor);


                actualizarVisualizacionPiso(nuevoValor);

               
                if (slider.getValue() == valorDestino) {
                    timerAnimacion.stop();

        
                    slider.setValue(valorDestino);


                    posicionarFlechaEnSlider();

            
                    actualizarVisualizacionPiso(valorDestino);

                    Timer timerFinal = new Timer(100, ev -> {
                        iniciarPausa(valorDestino);
                    });
                    timerFinal.setRepeats(false);
                    timerFinal.start();
                }
            });

            timerAnimacion.start();
    
        }
    
    
    private void iniciarPausa(int valorDestino) {


        slider.setValue(valorDestino);

        SwingUtilities.invokeLater(() -> {
            posicionarFlechaEnSlider();
            actualizarVisualizacionPiso(valorDestino); 
            actualizarLabelPiso(valorDestino); 
            flechaAscensor.repaint();
        });

 
        verificar(valorDestino);

        timerPausa = new Timer(2000, e -> {
            timerPausa.stop();
           

            SwingUtilities.invokeLater(() -> {
                posicionarFlechaEnSlider();
                actualizarVisualizacionPiso(valorDestino); 
            });

            procesarSiguiente();
        });

        timerPausa.setRepeats(false);
        timerPausa.start();
    }
      // Método para actualizar la flecha cuando cambia el tamaño de la ventana
    @Override
    public void paint(java.awt.Graphics g) {
        super.paint(g);
        // Actualizar posición de la flecha cuando se redibuja la ventana
        if (flechaAscensor != null && slider != null) {
            actualizarPosicionFlecha(slider.getValue());
        }
    }
    
    // Método para cuando se redimensiona la ventana
    private void formComponentResized(java.awt.event.ComponentEvent evt) {
 
        if (flechaAscensor != null && slider != null) {
            actualizarPosicionFlecha(slider.getValue());
        }
    }
    

    private void procesarSiguiente() {
        if (!colaDestinos.isEmpty()) {
            int siguiente = colaDestinos.poll();
           
            iniciarAnimacion(siguiente);
        } else {
            animacionEnCurso = false;
            destinoActual = -1;
           
        }
    }

    private void verificar(int valor) {

        piso1edificio.setSelected(false);
        piso2edificio.setSelected(false);
        piso3edificio.setSelected(false);
        piso1.setSelected(false);
        piso2.setSelected(false);
        piso3.setSelected(false);

      
        actualizarLabelPiso(valor);

        
        actualizarVisualizacionPiso(valor);

      
        SwingUtilities.invokeLater(() -> {
            posicionarFlechaEnSlider();
            repaint();
        });


    }

    private void actualizarLabelPiso(int valorPiso) {
       
        int numeroPiso = 0;
        if (valorPiso == 0) numeroPiso = 1;
        else if (valorPiso == 75) numeroPiso = 2;
        else if (valorPiso == 150) numeroPiso = 3;

    
        if (numero != null) {
            numero.setText(String.valueOf(numeroPiso));
        }
    }
    
    private void actualizarVisualizacionPiso(int valorPiso) {

        resetearColoresLabels();


        if (valorPiso == 0) {
            label_llamar1.setForeground(java.awt.Color.RED);
        } else if (valorPiso == 75) {
            label_llamar2.setForeground(java.awt.Color.RED);
        } else if (valorPiso == 150) {
            label_llamar3.setForeground(java.awt.Color.RED);
        }
    }

    
    private void resetearColoresLabels() {
        label_llamar1.setForeground(java.awt.Color.getColor("254 254 254"));
        label_llamar2.setForeground(java.awt.Color.getColor("254 254 254"));
        label_llamar3.setForeground(java.awt.Color.getColor("254 254 254"));
    }
    

    public void limpiarCola() {
        colaDestinos.clear();
        animacionEnCurso = false;
        if (timerAnimacion != null) timerAnimacion.stop();
        if (timerPausa != null) timerPausa.stop();
        
        // Deseleccionar todos los botones
        piso1edificio.setSelected(false);
        piso2edificio.setSelected(false);
        piso3edificio.setSelected(false);
        piso1.setSelected(false);
        piso2.setSelected(false);
        piso3.setSelected(false);
        
      
    }   
    // Método para obtener estado actual
    public String obtenerEstado() {
        return "Animación: " + (animacionEnCurso ? "En curso" : "Detenida") + 
               " | Cola: " + colaDestinos + 
               " | Destino actual: " + destinoActual;
    }   
    
    private void piso1edificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piso1edificioActionPerformed
        
        solicitarPiso(0);
        
        
        
        
    }//GEN-LAST:event_piso1edificioActionPerformed

    private void piso2edificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piso2edificioActionPerformed
                
        solicitarPiso(75);
        
    }//GEN-LAST:event_piso2edificioActionPerformed

    private void piso3edificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piso3edificioActionPerformed
        
        solicitarPiso(150);
        
    }//GEN-LAST:event_piso3edificioActionPerformed

    private void piso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piso1ActionPerformed
        // TODO add your handling code here:
        solicitarPiso(0);
    }//GEN-LAST:event_piso1ActionPerformed

    private void piso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piso2ActionPerformed
        // TODO add your handling code here:
        solicitarPiso(75);
    }//GEN-LAST:event_piso2ActionPerformed

    private void piso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piso3ActionPerformed
        // TODO add your handling code here:
        solicitarPiso(150);
    }//GEN-LAST:event_piso3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatMacDarkLaf());
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Failed to initialize FlatLaf Dark", ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ventana().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel flechaAscensor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel label_llamar1;
    private javax.swing.JLabel label_llamar2;
    private javax.swing.JLabel label_llamar3;
    private javax.swing.JLabel numero;
    private javax.swing.JToggleButton piso1;
    private javax.swing.JToggleButton piso1edificio;
    private javax.swing.JToggleButton piso2;
    private javax.swing.JToggleButton piso2edificio;
    private javax.swing.JToggleButton piso3;
    private javax.swing.JToggleButton piso3edificio;
    private javax.swing.JSlider slider;
    // End of variables declaration//GEN-END:variables
}
